dockutil
geerlingguy/mac-dev-playbook pull request #106
Opened 2021-04-12 11:31 UTC by dspolleke

Because upstream contributor does not respond I added the functionality and made it work. 

- fixed default (empty) variable
- fixed some strong language
- fixed the tags (added block)
- used command in stead of shell where possible. 
- loop vs with_items
-  added the default icons that Apple installs on that mile wide dock on Big Sur

2021-04-12 14:57 UTC, geerlingguy commented
Original PR for reference: https://github.com/geerlingguy/mac-dev-playbook/pull/84

2021-04-12 15:00 UTC, geerlingguy requested changes

2021-04-12 15:00 UTC, geerlingguy commented on default.config.yml
> +  - name: iTerm
This might not be installed on someone's computer. I'd rather keep things that are definitely there, like `Safari`, in the defaults.

2021-04-12 15:00 UTC, geerlingguy commented on tasks/extra-packages.yml
> +- name: Ensure extra packages
It looks like these changes snuck in from another PR?

2021-04-12 15:21 UTC, dspolleke commented on default.config.yml
> +dockitems_to_remove:
well, if i do, the tests will not reflect on the  changes it makes. But i can certainly try ;-)

2021-04-12 15:22 UTC, dspolleke commented on default.config.yml
> +  - name: iTerm
remove_spacers allready was sent to /dev/null in the tasks for it is not nicely implemented in dockutils. i will remove it.

2021-04-12 15:22 UTC, dspolleke commented on tasks/extra-packages.yml
> +- name: Ensure extra packages
have you still not merged that one? In the Netherlands we say " Twee woorden, negen letters: Duurt lang"

2021-04-12 15:36 UTC, dspolleke commented on default.config.yml
> +  - name: iTerm
created some sane defaults. will commit soon.

2021-04-12 15:36 UTC, dspolleke commented on main.yml
> +    - include_tasks: tasks/dock.yml
edited will commit soon

2021-04-12 17:35 UTC, dspolleke commented on tasks/extra-packages.yml
> +- name: Ensure extra packages
fixed

2021-05-07 15:18 UTC, merged

2021-05-07 15:27 UTC, geerlingguy commented
Merged, but made sure nothing is changed by default, and also changed a few vars and styling for consistency.