fix playbook to run terminal on remote hosts as wel
geerlingguy/mac-dev-playbook pull request #107
Opened 2021-04-12 13:17 UTC by dspolleke

https://github.com/geerlingguy/mac-dev-playbook/issues/102
also added tag

2021-05-15 03:57 UTC, geerlingguy requested changes
Can you rebase so this only includes the relevant changes?

2021-05-26 04:06 UTC, geerlingguy commented
It seems like you may be doing a merge/rebase, which means all the other changes are mixed in when I try previewing it on GitHub: https://github.com/geerlingguy/mac-dev-playbook/pull/107/files

Can you do a `git rebase master` and then `git push --force`—or alternately maybe just delete this PR/branch and create a new one? I could go grab the .patch from this PR and do it myself but it might be faster for you to :)

2021-05-27 17:04 UTC, geerlingguy requested changes

2021-05-27 17:04 UTC, geerlingguy commented on main.yml
> +    - name: Install global Ruby gems.
It looks like some other commits/changes made it to this PR too, including some different inventory bits too, and a few changes to the default config...

2021-05-27 17:12 UTC, dspolleke commented on main.yml
> +    - name: Install global Ruby gems.
updated main.yml and invetory to remove those

2021-05-27 17:18 UTC, geerlingguy requested changes

2021-05-27 17:18 UTC, geerlingguy commented on main.yml
> +    - import_tasks: tasks/dock.yml
Heh, this still seems to have persisted for some reason (looks like a duplicate import)

2021-05-27 17:18 UTC, geerlingguy commented on requirements.yml
> +collections:
For now, can you leave this out since it's not required if someone just installs `ansible` (the community version)?

2021-05-27 17:22 UTC, dspolleke commented on requirements.yml
> +collections:
sure, i can, but i added it because it did not work for me without it, and it will not install anything if the collection is already there.

2021-05-27 17:25 UTC, dspolleke commented on main.yml
> +    - import_tasks: tasks/dock.yml
it is alive!!!!

2021-05-27 18:39 UTC, geerlingguy approved these changes

2021-05-27 18:39 UTC, geerlingguy commented on tasks/terminal.yml
> +  ansible.builtin.copy:
```suggestion
  copy:
```

2021-05-27 18:39 UTC, geerlingguy commented
To keep the task in conformity with the other playbook tasks for now, I'm not using the 'FQCN' to call the `copy` module. At some point in the future I'll upgrade all my work to use FQCNs, but would rather not have them mixed in for now.

2021-05-27 18:40 UTC, geerlingguy commented on ansible.cfg
> +become = true
```suggestion
```

2021-05-27 18:40 UTC, geerlingguy commented on ansible.cfg
> +become = true
Also would like this gone just because it is useful to run the playbook without requiring sudo password many times (e.g. if just running `--tags dock`).

2021-05-27 18:41 UTC, merged