Ggvim
geerlingguy/mac-dev-playbook pull request #108
Opened 2021-04-12 16:31 UTC by dspolleke

https://github.com/geerlingguy/mac-dev-playbook#configuration-to-be-added

2021-04-12 18:08 UTC, StephenBrown2 commented on default.config.yml
> +dotfiles_repo: https://github.com/dspolleke/dotfiles.git
This should not change, at least not in this repo.

2021-04-12 18:09 UTC, StephenBrown2 commented on default.config.yml
> +#  - name: showoff
Space mistake:
```suggestion
# - name: showoff
```

2021-04-12 18:09 UTC, StephenBrown2 commented on inventory
> +#192.168.2.49
A local addition, should be removed

2021-04-12 20:31 UTC, dspolleke commented on default.config.yml
> +dotfiles_repo: https://github.com/dspolleke/dotfiles.git
leakage of my fork into upstream. Fixed

2021-04-12 20:32 UTC, dspolleke commented on default.config.yml
> +#  - name: showoff
leakage of my fork into upstream. Fixed

2021-04-12 20:32 UTC, dspolleke commented on inventory
> +#192.168.2.49
leakage of my fork into upstream. Fixed

2021-05-15 03:57 UTC, geerlingguy requested changes
Can you rebase with just the relevant changes?

2021-05-27 10:14 UTC, closed without merging

2021-05-27 10:14 UTC, dspolleke commented
new pr comming soon