Helpers to generate config.yml sections
geerlingguy/mac-dev-playbook pull request #123
Opened 2021-06-06 07:16 UTC by pleasemarkdarkly

This is what I used to speed up my population of the config.yml file and perhaps help someone trying this dotfiles setup.

2021-06-29 17:59 UTC, StephenBrown2 requested changes
Looks good. Not sure if it'll get merged, but I left some suggestions that I hope are helpful for you.

2021-06-29 17:59 UTC, StephenBrown2 commented on gen-config-helper.md
> +...then take a look a how well  `sed` works.
These steps are using `grep`, not `sed`...
```suggestion
...then take a look a how well `grep` works.
```

2021-06-29 17:59 UTC, StephenBrown2 commented on gen-config-helper.md
> +
Just a tip, awk can match things and operate on files itself, so you don't need to use grep or cat

```suggestion
You can build up your `config.yml` section by section. I piped the following commands to `pbcopy` and cleaned up in the `config.yml` file directly. 
```bash
awk '/tap/{print "  - "$2}' Brewfile | pbcopy
```
```bash
awk '/brew/{print "  - "$2 }' Brewfile | pbcopy
```
```bash
awk '/cask/{print "  - "$2 }' Brewfile | pbcopy
```
```bash
awk '/mas/{print "  - { id: "$4", name: "$2 "}"}' Brewfile | pbcopy
```

```

2021-06-29 17:59 UTC, StephenBrown2 commented on gen-config-helper.md
> +cat Brewfile| grep -e mas
grep can operate on files by itself, no need for cat:
```suggestion
grep -e tap Brewfile
```
```bash
grep -e brew Brewfile
```
```bash
grep -e cask Brewfile
```
```bash
grep -e mas Brewfile
```

2021-06-29 17:59 UTC, StephenBrown2 commented on gen-config-helper.md
> +  "cat Brewfile | grep -e mas |  awk '{print "  - { id: "$4", name: "$2 "}"}'"
Application of prior comments:

```suggestion
  "awk '/tap/{print "  - "$2}' Brewfile"
  "awk '/brew/{print "  - "$2 }' Brewfile"
  "awk '/mas/{print "  - { id: "$4", name: "$2 "}"}' Brewfile"
```

2021-06-29 17:59 UTC, StephenBrown2 commented on gen-config-helper.md
> +The brew file has 4 parts, taps, brew, cask, mas. For the most part `sed` will filter out the parts you need, first dump your `Brewfile`...
```suggestion
The brew file has 4 parts, taps, brew, cask, mas. For the most part `grep` will filter out the parts you need, first dump your `Brewfile`...
```

2021-07-01 10:56 UTC, pleasemarkdarkly commented on gen-config-helper.md
> +
Thank you, these are super helpful and of course I had forgotten awk and grep file manipulation.

2021-10-31 06:54 UTC, closed without merging